// Generates src/data/generated/linkedinQr.ts (LOT 4, B4): the QR code of the
// LinkedIn profile shown on the HoloCard back, as a module matrix (qrcode-generator,
// MIT, devDependency; nothing ships to the browser but the matrix). Error
// correction M. Run `npm run gen:assets` after changing profiles.linkedin in
// content.ts; a test checks the generated source matches it.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import qrcode from 'qrcode-generator';

const content = readFileSync(new URL('../src/data/content.ts', import.meta.url), 'utf8');
const url = content.match(/linkedin: "(https:\/\/[^"]+)"/)?.[1];
if (!url) throw new Error('gen-qr : profiles.linkedin introuvable dans content.ts');

const qr = qrcode(0, 'M');
qr.addData(url);
qr.make();
const size = qr.getModuleCount();
const rows = Array.from({ length: size }, (_, row) =>
    Array.from({ length: size }, (_, col) => (qr.isDark(row, col) ? '1' : '0')).join(''));

const { version } = JSON.parse(readFileSync(new URL('../node_modules/qrcode-generator/package.json', import.meta.url), 'utf8'));
const outUrl = new URL('../src/data/generated/linkedinQr.ts', import.meta.url);
mkdirSync(new URL('.', outUrl), { recursive: true });
writeFileSync(outUrl, `// Generated by scripts/gen-qr.mjs with qrcode-generator ${version} (MIT): do not edit.
// QR code (error correction M) of the URL below; one string per row, 1 = dark module.
export const linkedinQr = {
    source: ${JSON.stringify(url)},
    rows: [
${rows.map((row) => `        '${row}',`).join('\n')}
    ],
};
`);
console.log(`gen-qr : ${size} × ${size} modules pour ${url}`);
