// Generates src/data/generated/skillIcons.ts (LOT 4, B2): the Simple Icons logos
// (simple-icons, CC0-1.0, devDependency) of the skills listed in content.ts, and
// nothing else — no icon library ships to the browser. Run `npm run gen:assets`
// after adding a skill icon; a test checks every slug of content.ts is generated.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import * as simpleIcons from 'simple-icons';

const contentUrl = new URL('../src/data/content.ts', import.meta.url);
const outUrl = new URL('../src/data/generated/skillIcons.ts', import.meta.url);
const { version } = JSON.parse(readFileSync(new URL('../node_modules/simple-icons/package.json', import.meta.url), 'utf8'));

const slugs = [...new Set([...readFileSync(contentUrl, 'utf8').matchAll(/icon: "([a-z0-9]+)"/g)].map((m) => m[1]))].sort();
const bySlug = new Map(Object.values(simpleIcons).filter((icon) => icon?.slug).map((icon) => [icon.slug, icon]));

const entries = slugs.map((slug) => {
    const icon = bySlug.get(slug);
    if (!icon) throw new Error(`gen-icons : « ${slug} » absent de simple-icons ${version}`);
    return `    ${JSON.stringify(slug)}: { title: ${JSON.stringify(icon.title)}, hex: '#${icon.hex}', path: ${JSON.stringify(icon.path)} },`;
});

mkdirSync(new URL('.', outUrl), { recursive: true });
writeFileSync(outUrl, `// Generated by scripts/gen-icons.mjs from simple-icons ${version} (CC0-1.0): do not edit.
// The logos stay trademarks of their owners (simple-icons DISCLAIMER.md).
import type { SkillIcon } from '../../types/models';

export const SIMPLE_ICONS_VERSION = '${version}';

export const skillIcons: Record<string, SkillIcon> = {
${entries.join('\n')}
};
`);
console.log(`gen-icons : ${slugs.length} icônes (simple-icons ${version})`);
