// Logos: Simple Icons (CC0-1.0), generated by scripts/gen-icons.mjs; they stay
// trademarks of their owners (simple-icons DISCLAIMER.md).
import React, { type CSSProperties } from 'react';
import { skillEffects as fx } from '../../../data/effects';
import { readableTint } from '../../../utils/color';
import { useSkillIconMap, type SkillIconMap } from './skillIconsStore';
import styles from './TechIcon.module.scss';

export interface TechIconProps {
    /** Simple Icons slug; null: the generic chip logo */
    slug: string | null;
}

/** Brand colours readable on the badge background, computed once the icons are in */
let tints: Record<string, string> | null = null;
function brandTint(icons: SkillIconMap, slug: string): string {
    if (!tints) {
        const background = getComputedStyle(document.documentElement).getPropertyValue('--bg-deep').trim();
        tints = Object.fromEntries(Object.entries(icons).map(([key, icon]) => [key, readableTint(icon.hex, background, fx.iconContrast)]));
    }
    return tints[slug] ?? icons[slug].hex;
}

/**
 * Logo of a technology (LOT 4, S3): the Simple Icons path in the current
 * colour (its brand colour once the badge lights up, via `--brand`), or a
 * generic chip for the entries Simple Icons does not have (Java, HFSQL…).
 * Until the icons chunk is in, an empty slot of the same size (no shift).
 * Decorative: the badge text names the technology.
 */
const TechIcon: React.FC<TechIconProps> = ({ slug }) => {
    const icons = useSkillIconMap();
    if (!slug) return <span className={styles.generic} aria-hidden="true" />;
    const icon = icons?.[slug];
    if (!icons || !icon) return <span className={styles.slot} aria-hidden="true" />;
    return (
        <svg className={styles.icon} viewBox="0 0 24 24" aria-hidden="true" focusable="false"
            style={{ '--brand': brandTint(icons, slug) } as CSSProperties}>
            <path d={icon.path} />
        </svg>
    );
};

export default TechIcon;
